### PR TITLE
BO: Fix SQL error if customers are shared

### PR DESCRIPTION
**Pull request by shaffe-fr**
| Questions | Answers |
| --- | --- |
| Branch? | dev |
| Description? | SQL error when doing the ajax request to grider.php from the best customers statistics page |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Create two shops with the share customers settings enabled. Go the Best customers section, the SQL error will be visible in the result of the XHR request to the grider.php script. |

### CODE REVIEW

**Comment by shaffe-fr** [comment]
Anyone to merge this PR?

**Comment by mickaelandrieu** [comment]
This PR dont respect pour standards and so cant be merged. Why should de review it?

As far as I Can see you have been notified to update this PR (and others).

Mickaël

**Comment by shaffe-fr** [comment]
M'y bad, I forget to amend the commit... I'll do it today.

**Comment by shaffe-fr** [comment]
@mickaelandrieu  I amended the commit, is the PR compliant to PrestaShop standards?

**Comment by mickaelandrieu** [comment]
@shaffe-fr yes! thank you 👍

**Comment by shaffe-fr** [comment]
I'll clean the merge in the history asap.

**Comment by aleeks** [comment]
Hello @shaffe-fr 
This PR have to be done on dev & 1.7.0.x, not master

**Comment by shaffe-fr** [comment]
Hello @aleeks, OK, if I'm correct these branches was created yet when I opened the PR. I'll close this one to create a new.
How can I target two branches with a single PR? 
Thanks

**Comment by aleeks** [comment]
Hello @shaffe-fr 
I think you can't. Maybe dev was already here, but 1.7.0.x is a new one.

**Comment by aleeks** [comment]
I tried to switch branch, but you have 2 commit. So yes, make another PR with proper commit ! Thks

**Comment by shaffe-fr** [comment]
Ok, I'll do a new one on the dev branch.

**Pull request closed without merging**
