### PR TITLE
Release 2.0.3

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.0.3
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release Test

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
@Progi1984 there is a regression maybe linked to the fix of the PR #8 
https://drive.google.com/file/d/1E1fuphQoIwOb-XYFICAkBLMP5UiOoSjn/view
The visits counter is incremented even if the customers is not logged 
See the video I create an order from FO when I change the status order visits change. I create an order from the BO the visits status is incremented

**Comment by Progi1984** [comment]
@sarahdib Could you create an issue and linked to me ?

**Comment by sarahdib** [comment]
@Progi1984  done :)

**Comment by florine2623** [comment]
Hello @Progi1984 ,

I have an issue with the logo of the module. The old logo is still displayed.
It might be related to https://github.com/PrestaShop/statsbestcustomers/pull/17 (the text is OK)
With PR #20 :
Screenshot 2021-11-24 at 11 51 03
Without PR :
Screenshot 2021-11-24 at 11 51 07

Otherwise, the rest is OK !
Thanks!

**Comment by PierreRambaud** [comment]
@florine2623 I'm not able to reproduce:
image
I think it's a browser cache problem, not related to this PR :thinking:

**Comment by florine2623** [comment]
Hello @PierreRambaud ,

Thanks ! Indeed, after deleting my cache, everything is fine.
It is QA approved ✅

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
